version: '3.8'

services:
  app:
    image: apinotificacionesv2
    container_name: mi-apinotificacionesv2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3131:3131"
      - "3130:3130"
    environment:
      ASPNETCORE_URLS: https://+:3131;http://+:3130
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mi-apinotificacionesv2-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LUCIAno4226"
      # Omitimos las variables de entorno de AWS_ACCESS_KEY_ID y AWS_SECRET_ACCESS_KEY
    ports:
      - "1433:1433"
    volumes:
      - /sql/2019:/var/opt/mssql/data
      - /sql/2019:/var/opt/mssql/log
      - /sql/2019:/var/opt/mssql/secrets
